project:
    # 项目访问url,如不使用邮件功能可不配置
    url: http://www.easy-frame.top/easy-frame
    login:
        remember:
            # 是否开启记住我功能,安全性要求比较高的系统请改为false
            enabled: true
            # 记住我过期时间 默认30天 单位: 秒
            invalidate-time: 2592000
            # 开启记住我功能,敏感操作仍要客户登录 比如 支付/删除/审核
            security: true
    # 文件上传路径&静态文件存放路径
    file-upload-path: /home/data/easy-frame
    # 设置session失效的扫描时间, 清理用户直接关闭浏览器造成的孤立会话 默认为 30分钟
    session-validation-interval: 1800
server:
    port: 80
spring:
    redis:
        # Redis数据库索引（默认为0）
        database: 2
        # Redis服务器地址
        host: 127.0.0.1
        # Redis服务器连接端口MybatisPlusConfig
        port: 6379
        # Redis服务器连接密码（默认为空）
        password: teng1990
        jedis:
            pool:
                # 连接池最大连接数（使用负值表示没有限制）
                max-active: 8
                # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1
                # 连接池中的最大空闲连接
                max-idle: 8
                # 连接池中的最小空闲连接
                min-idle: 0
        # 连接超时时间 单位: 秒
        timeout: 10
        # 默认的数据过期时间 30 分钟 单位: 秒
        expire: 1800
    datasource:
        dynamic:
            datasource:
                master:
                    driver-class-name: com.mysql.cj.jdbc.Driver
                    url: jdbc:mysql://127.0.0.1:3306/easy-frame?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMulQueries=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
                    username: root
                    password: tengchong
# beetl
beetl:
    #是否检测文件变化
    resource-auto-check: false